//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gotcha.Models
{
    
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Draft
    {
        public int id_row { get; set; }
        [Required]
        public int fk_id_part { get; set; }
        [Required]
        public int fk_id_mach { get; set; }
        [Required]
        public System.Nullable<int> version { get; set; }
    
        public virtual Machine Machine { get; set; }
        public virtual Part Part { get; set; }
    }
}
