//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gotcha.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Processing
    {
        public int id_row { get; set; }
        [Required]
        public int fk_id_part { get; set; }
        [Required]
        public int fk_id_mod { get; set; }
    
        public virtual Modification Modification { get; set; }
        public virtual Part Part { get; set; }
    }
}
